nodeid = "node2"
debug = true
beacon-period = true
generate-status-reports = false
parallel-bundle-processing = false
webport = 4002
workdir = "/tmp/dtn7-ecla2"
db = "mem"

[routing]
strategy = "epidemic"

[core]
janitor = "10s"

[discovery]
interval = "120s"
peer-timeout = "300s"

[endpoints]
# local endpoints are always reachable under dtn://<nodeid>/<localname>
local.0 = "incoming"
local.1 = "null"

[ecla]
enabled  = true
tcp_port = 0
